#!/usr/bin/env python3
"""Generate musa/docs/supported_ops.md from the kernel registration macros.

Scans `musa/ep/src/kernels/*.cc` for `ONNX_OPERATOR_VERSIONED_KERNEL_EX(name,
domain, startver, endver, builder, kernel_class)` and extracts every
`AddTypeConstraint("X", <set>)` from the builder expression. Type-set helper
functions like `FloatTensorTypes()` / `AllTensorTypes()` are resolved by
scanning the same source for their `return { ... }` body, so adding a new
helper / dtype in C++ automatically shows up in the doc.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Iterable

REPO = Path(__file__).resolve().parents[1]
KERNELS_DIR = REPO / "musa" / "ep" / "src" / "kernels"
OUTPUT = REPO / "musa" / "docs" / "supported_ops.md"

# Pretty names for ONNX_TENSOR_ELEMENT_DATA_TYPE_* enum tokens.
DTYPE_NAMES = {
    "FLOAT": "float32",
    "UINT8": "uint8",
    "INT8": "int8",
    "UINT16": "uint16",
    "INT16": "int16",
    "INT32": "int32",
    "INT64": "int64",
    "STRING": "string",
    "BOOL": "bool",
    "FLOAT16": "float16",
    "DOUBLE": "float64",
    "UINT32": "uint32",
    "UINT64": "uint64",
    "BFLOAT16": "bfloat16",
}

DOMAIN_NAMES = {
    "kOnnxDomain": "ai.onnx",
    "kMSDomain": "com.microsoft",
}

_MACRO_RE = re.compile(
    r"ONNX_OPERATOR_VERSIONED_KERNEL_EX\s*\(\s*"
    r"(?P<name>\w+)\s*,\s*"
    r"(?P<domain>\w+)\s*,\s*"
    r"(?P<start>\d+)\s*,\s*"
    r"(?P<end>\d+)\s*,\s*"
    r"(?P<builder>.+?)\s*,\s*"
    r"(?P<kclass>\w+)\s*\)",
    re.DOTALL,
)

_CONSTRAINT_RE = re.compile(
    r'AddTypeConstraint\s*\(\s*"(?P<key>[^"]+)"\s*,\s*(?P<expr>[^)]+(?:\([^)]*\)[^)]*)*)\)'
)

_HELPER_RE = re.compile(
    r"std::vector<const OrtDataType\*>\s+(?P<name>\w+)\s*\(\s*\)\s*\{[^}]*?return\s*\{(?P<body>[^}]*)\}",
    re.DOTALL,
)

_DTYPE_TOKEN_RE = re.compile(r"ONNX_TENSOR_ELEMENT_DATA_TYPE_(\w+)")


def _read_sources() -> list[tuple[Path, str]]:
    # Kernel implementations live in `*.cc`; shared type-constraint helpers
    # (AllTensorTypes / FloatTensorTypes / ...) live in `common/*.h`. Both are
    # scanned: the headers populate the helper table, the sources the macros.
    paths = sorted(KERNELS_DIR.glob("*.cc")) + sorted(KERNELS_DIR.glob("common/*.h"))
    return [(p, p.read_text()) for p in paths]


def _strip_block_comments(text: str) -> str:
    return re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)


def _strip_line_comments(text: str) -> str:
    return re.sub(r"//[^\n]*", "", text)


def _build_helper_table(sources: Iterable[tuple[Path, str]]) -> dict[str, list[str]]:
    """Map helper-function name (e.g. `FloatTensorTypes`) -> list of dtype names."""
    table: dict[str, list[str]] = {}
    for _path, text in sources:
        for m in _HELPER_RE.finditer(text):
            tokens = _DTYPE_TOKEN_RE.findall(m.group("body"))
            table[m.group("name")] = [DTYPE_NAMES.get(t, t.lower()) for t in tokens]
    return table


def _resolve_constraint(expr: str, helpers: dict[str, list[str]]) -> list[str]:
    """Resolve a type-constraint RHS like `AllTensorTypes()` or
    `GetTensorType(ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT)` to a list of dtype names.
    """
    expr = expr.strip()
    direct = _DTYPE_TOKEN_RE.findall(expr)
    if direct:
        return [DTYPE_NAMES.get(t, t.lower()) for t in direct]
    for helper_name, dtypes in helpers.items():
        if helper_name in expr:
            return dtypes
    return ["?"]


def _format_types(constraints: dict[str, list[str]]) -> str:
    if not constraints:
        return "—"
    parts = []
    for key, dtypes in constraints.items():
        parts.append(f"`{key}`: {', '.join(dtypes)}")
    return "<br>".join(parts)


def collect_ops() -> list[dict]:
    sources = _read_sources()
    helpers = _build_helper_table(sources)
    ops: list[dict] = []
    for path, raw in sources:
        text = _strip_line_comments(_strip_block_comments(raw))
        for m in _MACRO_RE.finditer(text):
            constraints_in_order: dict[str, list[str]] = {}
            for c in _CONSTRAINT_RE.finditer(m.group("builder")):
                constraints_in_order[c.group("key")] = _resolve_constraint(c.group("expr"), helpers)
            ops.append(
                {
                    "op": m.group("name"),
                    "domain": DOMAIN_NAMES.get(m.group("domain"), m.group("domain")),
                    "since": int(m.group("start")),
                    "until": int(m.group("end")),
                    "kernel_class": m.group("kclass"),
                    "source": path.name,
                    "types": _format_types(constraints_in_order),
                }
            )
    ops.sort(key=lambda x: (x["domain"], x["op"], x["since"]))
    return ops


def render(ops: list[dict]) -> str:
    lines = [
        "<!-- AUTO-GENERATED by scripts/gen_supported_ops.py. DO NOT EDIT BY HAND. -->",
        "# Supported Ops",
        "",
        f"Total registered kernels: **{len(ops)}**",
        "",
        "| Op | Domain | Opset (since–until) | Type constraints | Source |",
        "| --- | --- | --- | --- | --- |",
    ]
    for op in ops:
        lines.append(
            f"| `{op['op']}` | `{op['domain']}` | {op['since']}–{op['until']} | "
            f"{op['types']} | `{op['source']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ops = collect_ops()
    if not ops:
        print("[gen_supported_ops] no kernels found", file=sys.stderr)
        return 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(ops))
    print(f"[gen_supported_ops] wrote {len(ops)} kernels -> {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
